// <auto-generated />
namespace PharmacyAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PharmacyAPIPrototype123Test_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PharmacyAPIPrototype123Test_db));
        
        string IMigrationMetadata.Id
        {
            get { return "201711211925290_PharmacyAPIPrototype123Test_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
