// <auto-generated />
namespace PharmacyAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _321 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_321));
        
        string IMigrationMetadata.Id
        {
            get { return "201712061834046_321"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
